### GET SONGS
GET http://localhost:3000/songs

### GET SONG
GET http://localhost:3000/songs/2

### DELETE SONG
DELETE http://localhost:3000/songs/4

### POST SONG
POST http://localhost:3000/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdmluQHNvbG9tb24uaWQiLCJ1c2VySWQiOjQsImFydGlzdElkIjoyLCJpYXQiOjE3MTE2MDA1MjUsImV4cCI6MTcxMTYwNDEyNX0.AYZ7xqRRo2LCS9qjw5-C2jUSqhGffbLEr6xRCY_zU20
Content-Type: application/json

{
  "title": "Lagu 3",
  "artists": [
    2
  ],
  "releasedDate": "2003-09-07",
  "duration": "3:51",
  "lyrics": "You can dance you can jive having the time of your life"
}

### PUT SONG
PUT http://localhost:3000/songs/3
Content-Type: application/json

{
  "title": "Dancing Doni",
  "artists": [
    "ABBA"
  ],
  "releasedDate": "1976-08-15",
  "duration": "3:51",
  "lyrics": "You can dance you can jive having the time of your life"
}


### USERS
### REGISTER USERS
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "novin",
  "lastName": "ardian",
  "email": "novin@solomon.id",
  "password": "novinnovin"
}

### LOGIN USERS
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "novin@solomon.id",
  "password": "novinnovin"
}

### PROFILE
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHNvbG9tb24uaWQiLCJzdWIiOjIsImlhdCI6MTcxMTU5NjYzNywiZXhwIjoxNzExNjAwMjM3fQ.H3RUenG7zafdeosKQoAZnX3Jjx-6Tox2q2QwvnZNC0o

### PROFILE
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHNvbG9tb24uaWQiLCJzdWIiOjIsImlhdCI6MTcxMTU5NjYzNywiZXhwIjoxNzExNjAwMjM3fQ.H3RUenG7zafdeosKQoAZnX3Jjx-6Tox2q2QwvnZNC0o